### ISSUE TITLE
from qtrader.core.event_engine import BarEventEngineRecorder, BarEventEngine  error

### ISSUE THREAD

**Issue by yangzhipeng1108** [josephchenhk/qtrader#19]
Traceback (most recent call last):
  File "E:/python/yovole/ai-project/stock/qtrader-master/examples/demo_strategy/qunater.py", line 3, in <module>
    from qtrader.core.event_engine import BarEventEngineRecorder, BarEventEngine
  File "event_engine.py", line 30, in init qtrader.core.event_engine
  File "engine.py", line 37, in init qtrader.core.engine
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\qtrader\core\portfolio.py", line 22, in <module>
    from qtrader.gateways import BaseGateway
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\qtrader\gateways\__init__.py", line 32, in <module>
    from .cqg import CqgGateway
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\qtrader\gateways\cqg\__init__.py", line 18, in <module>
    from .cqg_gateway import CqgGateway
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\qtrader\gateways\cqg\cqg_gateway.py", line 23, in <module>
    from qtrader.gateways.cqg.wrapper.cqg_api import CQGAPI
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\qtrader\gateways\cqg\wrapper\cqg_api.py", line 33, in <module>
    from qtrader.gateways.cqg.wrapper.CELEnvironment import CELSinkBase
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\qtrader\gateways\cqg\wrapper\CELEnvironment.py", line 10, in <module>
    win32com.client.gencache.EnsureModule('{51F35562-AEB4-4AB3-99E8-AC9666344B64}', 0, 4, 0)
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\gencache.py", line 598, in EnsureModule
    module = MakeModuleForTypelib(
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\gencache.py", line 315, in MakeModuleForTypelib
    makepy.GenerateFromTypeLibSpec(
  File "C:\Users\yangzhipeng\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\makepy.py", line 257, in GenerateFromTypeLibSpec
    tlb = pythoncom.LoadRegTypeLib(typelibCLSID, major, minor, lcid)
pywintypes.com_error: (-2147319779, '库没有注册。', None, None)

**Comment by josephchenhk** [comment]
Hi，你不用cqg的话，应该不需要装这个的。你确定是下载了最新的版本了吗？在gateways/cqg/__init__.py文件里，应该是如下这样：

```
try:
    from .cqg_gateway import CqgGateway
except ImportError as e:
    print(f"{e.__class__}: {e.msg}")

try:
    from .cqg_fees import CQGFees
except ImportError as e:
    print(f"{e.__class__}: {e.msg}")
```

**Comment by yangzhipeng1108** [comment]
Run a Backtest  使用这个例子测试的
gateways/cqg/__init__.py  这里是正确的
还是报错

**Comment by josephchenhk** [comment]
> Run a Backtest 使用这个例子测试的 gateways/cqg/**init**.py 这里是正确的 还是报错

我这里没法重现，我再研究下。你可以先注释这几行，不影响跑回测。

**Comment by josephchenhk** [comment]
Close as this is legacy.
