### ISSUE TITLE
两个建议，1开源core,2去掉第三方强制依赖

### ISSUE THREAD

**Issue by ruifeng96150** [josephchenhk/qtrader#6]
你好，最近正在想找一个合适的开源回测系统，看到这个项目，试跑了下，发现几个问题：

1 没有完全开源，这样别人就不敢使用这样项目，有了问题无法解决
2 跑demo配置不是很方便，我的是Linux系统，只想跑下回测，为什么没有还需要我安装tutu，ibapi，win32com等等？
3 DATA_FFILL又是什么 ？

```
<class 'ModuleNotFoundError'>: No module named 'futu'
<class 'ImportError'>: cannot import name 'FutuGateway' from 'qtrader.gateways.futu' (/home/terry/Documents/demos/qtrader/qtrader/gateways/futu/__init__.py)
<class 'ModuleNotFoundError'>: No module named 'ibapi'
<class 'ImportError'>: cannot import name 'IbGateway' from 'qtrader.gateways.ib' (/home/terry/Documents/demos/qtrader/qtrader/gateways/ib/__init__.py)
<class 'ModuleNotFoundError'>: No module named 'win32com'
<class 'ImportError'>: cannot import name 'CqgGateway' from 'qtrader.gateways.cqg' (/home/terry/Documents/demos/qtrader/qtrader/gateways/cqg/__init__.py)
Traceback (most recent call last):
  File "main_demo.py", line 24, in <module>
    from qtrader.core.event_engine import BarEventEngineRecorder, BarEventEngine
  File "event_engine.py", line 35, in init qtrader.qtrader.core.event_engine
ImportError: cannot import name DATA_FFILL
```

**Comment by josephchenhk** [comment]
Thanks.

1. core部分经过大量的测试，已经很稳定，基于性能和其他考虑，暂时进行了封装，开发者只需要当作lib使用便可。后续有更改我会及时更新。
2. 这些只是warning，只是跑回测的话，可以不用理会
3. DATA_FFILL是将回测数据向前覆盖（forward fill），是最近添加的设置，需要在qtrader_config.py 里面加上一行“DATA_FFILL = True”，我已经更新了相应的sample，感谢提醒。
